### ISSUE TITLE
Recent versions of `parse_packwerk` are only compatible with unreleased Packwerk 3

### ISSUE THREAD

**Issue by iMacTia** [rubyatscale/parse_packwerk#19]
Since [v0.15.0](https://github.com/rubyatscale/parse_packwerk/releases/tag/v0.15.0), `parse_packwerk` switched to the new `package_todo.yml` standard, which will come in effect with Packwerk 3.
However, Packwerk 3 has not been released yet, so these can only work against Packwerk's `main` branch.

This caused some confusion because many other `rubyatscale` gems internally depend on this gem, but there's no restriction on the Packwerk version in the gems dependencies, causing issues when a project is still using Packwerk 2.

I understand being on a `0.x` release line means we should expect breaking changes, but this seems like an issue with dependencies that could easily be solved with some proper version restrictions in the `gemspec`.
Is there a plan on how to address this?

**Comment by alexevanczuk** [comment]
Hey @iMacTia thanks again for filing this issue. In the long-term, once `packwerk` 3 is released, we can probably stop pointing directly at `main` and instead have a version based constraint. I'm hoping packwerk 3 will be coming soon!

In the short-term, part of the problem is that `parse_packwerk` is explicitly intended to *not* depend on `packwerk` so as to be free of its dependencies and to be safely used as a production dependency.

Would it help if we added the version restriction to any of the gems that do depend on `packwerk`, such as `use_packs`? Let me know what you think. Thank you!

**Comment by iMacTia** [comment]
Ah I see why this is tricky...
If we can set the dependency explicitly, then I'm not sure there's a way to deal with this automatically.
In which case, how about making this more explicit in the readme? e.g. a compatibility table:

| Packwerk | ParsePackwerk |
| :---: | :---: |
| v2 | <= 0.14.x |
| v3 | >= 0.15.x |

> Would it help if we added the version restriction to any of the gems that do depend on packwerk, such as use_packs?
This might help others, so I'd still consider it, but it wouldn't help us since we only directly depend on `parse_packwerk` in production

**Comment by oskarpearson** [comment]
👋 We can probably close this now, right? Packwerk 3 has now been released for a couple of weeks. I'm guessing we don't need to worry about backwards compatibility for Packwerk 2 in the README forever.

**Comment by alexevanczuk** [comment]
That would work for me, what do you think @iMacTia ? That would simplify things quite a bit if we just drop references to packwerk 2.

**Comment by iMacTia** [comment]
Yup, we've already upgraded to Packwerk 3 anyway, so this is not going to bother us anymore, happy to close 😄 !
